from django.db.models import TextChoices


class StatusChoices(TextChoices):
    PENDING = "PENDING", "Pending"
    CONFIRMED = "CONFIRMED", "Confirmed"
    CANCELLED = "CANCELLED", "Cancelled"
    COMPLETED = "COMPLETED", "Completed"


class RoleChoices(TextChoices):
    USER = "USER", "User"
    ADMIN = "ADMIN", "Admin"
    DOCTOR = "DOCTOR", "Doctor"
    STAFF = "STAFF", "Staff"


class GenderChoices(TextChoices):
    MALE = "MALE", "Male"
    FEMALE = "FEMALE", "Female"
    OTHER = "OTHER", "Other"


class BloodGroupChoices(TextChoices):
    A_POSITIVE = "A+", "A+"
    A_NEGATIVE = "A-", "A-"
    B_POSITIVE = "B+", "B+"
    B_NEGATIVE = "B-", "B-"
    AB_POSITIVE = "AB+", "AB+"
    AB_NEGATIVE = "AB-", "AB-"
    O_POSITIVE = "O+", "O+"
    O_NEGATIVE = "O-", "O-"


class TestTypes(TextChoices):
    BLOOD_TEST = "BLOOD_TEST", "BLOOD_TEST"
    URINE_TEST = "URINE_TEST", "URINE_TEST"
    X_RAY = "X_RAY", "X_RAY"
    MRI = "MRI", "MRI"
    CT_SCAN = "CT_SCAN", "CT_SCAN"
    ULTRASOUND = "ULTRASOUND", "ULTRASOUND"
    ECG = "ECG", "ECG"
    ECHO = "ECHO", "ECHO"
    BLOOD_PRESSURE = "BLOOD_PRESSURE", "BLOOD_PRESSURE"
    LIVER_FUNCTION = "LIVER_FUNCTION", "LIVER_FUNCTION"
    KIDNEY_FUNCTION = "KIDNEY_FUNCTION", "KIDNEY_FUNCTION"
    THYROID_TEST = "THYROID_TEST", "THYROID_TEST"
    LIPID_PROFILE = "LIPID_PROFILE", "LIPID_PROFILE"
    CBC = "CBC", "CBC"
    STOOL_TEST = "STOOL_TEST", "STOOL_TEST"
    BIOPSY = "BIOPSY", "BIOPSY"
    ALLERGY_TEST = "ALLERGY_TEST", "ALLERGY_TEST"
    HIV_TEST = "HIV_TEST", "HIV_TEST"
    COVID_19_TEST = "COVID_19_TEST", "COVID_19_TEST"
    PULMONARY_FUNCTION = "PULMONARY_FUNCTION", "PULMONARY_FUNCTION"
    EYE_TEST = "EYE_TEST", "EYE_TEST"
    DEXA_SCAN = "DEXA_SCAN", "DEXA_SCAN"
    MAMMOGRAM = "MAMMOGRAM", "MAMMOGRAM"
    PAP_SMEAR = "PAP_SMEAR", "PAP_SMEAR"
    GENETIC_TEST = "GENETIC_TEST", "GENETIC_TEST"
    MICROBIOLOGY_TEST = "MICROBIOLOGY_TEST", "MICROBIOLOGY_TEST"
    CARDIAC_STRESS_TEST = "CARDIAC_STRESS_TEST", "CARDIAC_STRESS_TEST"
    HORMONE_TEST = "HORMONE_TEST", "HORMONE_TEST"
    GASTROSCOPY = "GASTROSCOPY", "GASTROSCOPY"
    COLONOSCOPY = "COLONOSCOPY", "COLONOSCOPY"
    CYSTOSCOPY = "CYSTOSCOPY", "CYSTOSCOPY"
    PET_SCAN = "PET_SCAN", "PET_SCAN"
