# Generated by Django 5.0.6 on 2024-07-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
