# Generated by Django 5.0.6 on 2024-07-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usermodel_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='schedule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
