# Generated by Django 5.0.6 on 2024-06-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_usermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
