# Generated by Django 5.0.6 on 2024-09-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_usermodel_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('STAFF', 'Staff')], default='user', max_length=20),
        ),
    ]
