# Generated by Django 5.0.6 on 2024-09-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_usermodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profilePicture',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
