# Generated by Django 5.0.6 on 2024-06-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_usermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('USER', 'user'), ('ADMIN', 'admin'), ('DOCTOR', 'doctor'), ('STAFF', 'staff')], default='user', max_length=20),
        ),
    ]
