# Generated by Django 5.0.6 on 2024-09-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_usermodel_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
