# Generated by Django 5.0.6 on 2024-07-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_usermodel_available_days_usermodel_consultation_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
