# Generated by Django 5.0.6 on 2024-08-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
