# Generated by Django 5.0.6 on 2024-09-01 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointmentmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='tests_required',
            field=models.CharField(blank=True, choices=[('BLOOD_TEST', 'Blood Test'), ('URINE_TEST', 'Urine Test'), ('X_RAY', 'X-Ray'), ('MRI', 'MRI'), ('CT_SCAN', 'CT Scan'), ('ULTRASOUND', 'Ultrasound'), ('ECG', 'ECG (Electrocardiogram)'), ('ECHO', 'Echocardiogram'), ('BLOOD_PRESSURE', 'Blood Pressure Test'), ('LIVER_FUNCTION', 'Liver Function Test'), ('KIDNEY_FUNCTION', 'Kidney Function Test'), ('THYROID_TEST', 'Thyroid Test'), ('LIPID_PROFILE', 'Lipid Profile'), ('CBC', 'Complete Blood Count (CBC)'), ('STOOL_TEST', 'Stool Test'), ('BIOPSY', 'Biopsy'), ('ALLERGY_TEST', 'Allergy Test'), ('HIV_TEST', 'HIV Test'), ('COVID_19_TEST', 'COVID-19 Test'), ('PULMONARY_FUNCTION', 'Pulmonary Function Test'), ('EYE_TEST', 'Eye Test'), ('DEXA_SCAN', 'DEXA Scan (Bone Density Test)'), ('MAMMOGRAM', 'Mammogram'), ('PAP_SMEAR', 'Pap Smear'), ('GENETIC_TEST', 'Genetic Test'), ('MICROBIOLOGY_TEST', 'Microbiology Test'), ('CARDIAC_STRESS_TEST', 'Cardiac Stress Test'), ('HORMONE_TEST', 'Hormone Test'), ('GASTROSCOPY', 'Gastroscopy'), ('COLONOSCOPY', 'Colonoscopy'), ('CYSTOSCOPY', 'Cystoscopy'), ('PET_SCAN', 'PET Scan')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='TestAndResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('BLOOD_TEST', 'Blood Test'), ('URINE_TEST', 'Urine Test'), ('X_RAY', 'X-Ray'), ('MRI', 'MRI'), ('CT_SCAN', 'CT Scan'), ('ULTRASOUND', 'Ultrasound'), ('ECG', 'ECG (Electrocardiogram)'), ('ECHO', 'Echocardiogram'), ('BLOOD_PRESSURE', 'Blood Pressure Test'), ('LIVER_FUNCTION', 'Liver Function Test'), ('KIDNEY_FUNCTION', 'Kidney Function Test'), ('THYROID_TEST', 'Thyroid Test'), ('LIPID_PROFILE', 'Lipid Profile'), ('CBC', 'Complete Blood Count (CBC)'), ('STOOL_TEST', 'Stool Test'), ('BIOPSY', 'Biopsy'), ('ALLERGY_TEST', 'Allergy Test'), ('HIV_TEST', 'HIV Test'), ('COVID_19_TEST', 'COVID-19 Test'), ('PULMONARY_FUNCTION', 'Pulmonary Function Test'), ('EYE_TEST', 'Eye Test'), ('DEXA_SCAN', 'DEXA Scan (Bone Density Test)'), ('MAMMOGRAM', 'Mammogram'), ('PAP_SMEAR', 'Pap Smear'), ('GENETIC_TEST', 'Genetic Test'), ('MICROBIOLOGY_TEST', 'Microbiology Test'), ('CARDIAC_STRESS_TEST', 'Cardiac Stress Test'), ('HORMONE_TEST', 'Hormone Test'), ('GASTROSCOPY', 'Gastroscopy'), ('COLONOSCOPY', 'Colonoscopy'), ('CYSTOSCOPY', 'Cystoscopy'), ('PET_SCAN', 'PET Scan')], max_length=100)),
                ('test_name', models.CharField(max_length=100)),
                ('test_fees_paid_token', models.CharField(max_length=30, unique=True)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('test_result_available', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='test_reports/')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_test', to='appointments.appointmentmodel')),
            ],
        ),
    ]
