# Generated by Django 5.0.6 on 2024-09-04 09:55

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointmentmodel_tests_required_testandresultmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='tests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BLOOD_TEST', 'Blood Test'), ('URINE_TEST', 'Urine Test'), ('X_RAY', 'X-Ray'), ('MRI', 'MRI'), ('CT_SCAN', 'CT Scan'), ('ULTRASOUND', 'Ultrasound'), ('ECG', 'ECG (Electrocardiogram)'), ('ECHO', 'Echocardiogram'), ('BLOOD_PRESSURE', 'Blood Pressure Test'), ('LIVER_FUNCTION', 'Liver Function Test'), ('KIDNEY_FUNCTION', 'Kidney Function Test'), ('THYROID_TEST', 'Thyroid Test'), ('LIPID_PROFILE', 'Lipid Profile'), ('CBC', 'Complete Blood Count (CBC)'), ('STOOL_TEST', 'Stool Test'), ('BIOPSY', 'Biopsy'), ('ALLERGY_TEST', 'Allergy Test'), ('HIV_TEST', 'HIV Test'), ('COVID_19_TEST', 'COVID-19 Test'), ('PULMONARY_FUNCTION', 'Pulmonary Function Test'), ('EYE_TEST', 'Eye Test'), ('DEXA_SCAN', 'DEXA Scan (Bone Density Test)'), ('MAMMOGRAM', 'Mammogram'), ('PAP_SMEAR', 'Pap Smear'), ('GENETIC_TEST', 'Genetic Test'), ('MICROBIOLOGY_TEST', 'Microbiology Test'), ('CARDIAC_STRESS_TEST', 'Cardiac Stress Test'), ('HORMONE_TEST', 'Hormone Test'), ('GASTROSCOPY', 'Gastroscopy'), ('COLONOSCOPY', 'Colonoscopy'), ('CYSTOSCOPY', 'Cystoscopy'), ('PET_SCAN', 'PET Scan')], max_length=356, null=True),
        ),
    ]
