# Generated by Django 5.0.6 on 2024-09-06 08:35

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointmentmodel_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='tests_required',
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='tests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BLOOD_TEST', 'BLOOD_TEST'), ('URINE_TEST', 'URINE_TEST'), ('X_RAY', 'X_RAY'), ('MRI', 'MRI'), ('CT_SCAN', 'CT_SCAN'), ('ULTRASOUND', 'ULTRASOUND'), ('ECG', 'ECG'), ('ECHO', 'ECHO'), ('BLOOD_PRESSURE', 'BLOOD_PRESSURE'), ('LIVER_FUNCTION', 'LIVER_FUNCTION'), ('KIDNEY_FUNCTION', 'KIDNEY_FUNCTION'), ('THYROID_TEST', 'THYROID_TEST'), ('LIPID_PROFILE', 'LIPID_PROFILE'), ('CBC', 'CBC'), ('STOOL_TEST', 'STOOL_TEST'), ('BIOPSY', 'BIOPSY'), ('ALLERGY_TEST', 'ALLERGY_TEST'), ('HIV_TEST', 'HIV_TEST'), ('COVID_19_TEST', 'COVID_19_TEST'), ('PULMONARY_FUNCTION', 'PULMONARY_FUNCTION'), ('EYE_TEST', 'EYE_TEST'), ('DEXA_SCAN', 'DEXA_SCAN'), ('MAMMOGRAM', 'MAMMOGRAM'), ('PAP_SMEAR', 'PAP_SMEAR'), ('GENETIC_TEST', 'GENETIC_TEST'), ('MICROBIOLOGY_TEST', 'MICROBIOLOGY_TEST'), ('CARDIAC_STRESS_TEST', 'CARDIAC_STRESS_TEST'), ('HORMONE_TEST', 'HORMONE_TEST'), ('GASTROSCOPY', 'GASTROSCOPY'), ('COLONOSCOPY', 'COLONOSCOPY'), ('CYSTOSCOPY', 'CYSTOSCOPY'), ('PET_SCAN', 'PET_SCAN')], max_length=356, null=True),
        ),
        migrations.AlterField(
            model_name='testandresultmodel',
            name='test_type',
            field=models.CharField(choices=[('BLOOD_TEST', 'BLOOD_TEST'), ('URINE_TEST', 'URINE_TEST'), ('X_RAY', 'X_RAY'), ('MRI', 'MRI'), ('CT_SCAN', 'CT_SCAN'), ('ULTRASOUND', 'ULTRASOUND'), ('ECG', 'ECG'), ('ECHO', 'ECHO'), ('BLOOD_PRESSURE', 'BLOOD_PRESSURE'), ('LIVER_FUNCTION', 'LIVER_FUNCTION'), ('KIDNEY_FUNCTION', 'KIDNEY_FUNCTION'), ('THYROID_TEST', 'THYROID_TEST'), ('LIPID_PROFILE', 'LIPID_PROFILE'), ('CBC', 'CBC'), ('STOOL_TEST', 'STOOL_TEST'), ('BIOPSY', 'BIOPSY'), ('ALLERGY_TEST', 'ALLERGY_TEST'), ('HIV_TEST', 'HIV_TEST'), ('COVID_19_TEST', 'COVID_19_TEST'), ('PULMONARY_FUNCTION', 'PULMONARY_FUNCTION'), ('EYE_TEST', 'EYE_TEST'), ('DEXA_SCAN', 'DEXA_SCAN'), ('MAMMOGRAM', 'MAMMOGRAM'), ('PAP_SMEAR', 'PAP_SMEAR'), ('GENETIC_TEST', 'GENETIC_TEST'), ('MICROBIOLOGY_TEST', 'MICROBIOLOGY_TEST'), ('CARDIAC_STRESS_TEST', 'CARDIAC_STRESS_TEST'), ('HORMONE_TEST', 'HORMONE_TEST'), ('GASTROSCOPY', 'GASTROSCOPY'), ('COLONOSCOPY', 'COLONOSCOPY'), ('CYSTOSCOPY', 'CYSTOSCOPY'), ('PET_SCAN', 'PET_SCAN')], max_length=100),
        ),
    ]
